name: MacroChallengeTeam2.xcodeproj
options:
  bundleIdPrefix: Team2.MacroChallengeTeam2
packages:
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.5.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.6.0
targets:
  Macro Challenge Team2:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    info:
      path: MacroChallengeTeam2/Info.plist
      properties:
        UIApplicationSceneManifest:
              UIApplicationSupportsMultipleScenes: false
              UISceneConfigurations:
                UIWindowSceneSessionRoleApplication:
                  - UISceneConfigurationName: Default Configuration
                    UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate	
    postCompileScripts:
      - path: swiftlint.sh
        name: SwiftLint
    sources:
      - MacroChallengeTeam2
    dependencies:
      - package: RxSwift
      - package: SnapKit
