name: MacroChallengeTeam2
options:
  bundleIdPrefix: Team2.MacroChallengeTeam2
packages:
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.5.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.6.0
  SocketIO:
    url: https://github.com/socketio/socket.io-client-swift
    from: 16.0.1
targets:
  Macro Challenge Team2:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    info:
      path: MacroChallengeTeam2/Info.plist
      properties:
        UIApplicationSceneManifest:
              UIApplicationSupportsMultipleScenes: false
              UISceneConfigurations:
                UIWindowSceneSessionRoleApplication:
                  - UISceneConfigurationName: Default Configuration
                    UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIAppFonts: [SF-Pro-Rounded-Bold.otf, 
		     SF-Pro-Rounded-Black.otf,
		     SF-Pro-Rounded-Heavy.otf,
        	     SF-Pro-Rounded-Light.otf,
        	     SF-Pro-Rounded-Medium.otf,
            	     SF-Pro-Rounded-Regular.otf,
        	     SF-Pro-Rounded-Semibold.otf,
        	     SF-Pro-Rounded-Thin.otf,
        	     SF-Pro-Rounded-Ultralight.otf,
        	     FiraCode-Regular.ttf,]
    postCompileScripts:
      - path: swiftlint.sh
        name: SwiftLint
    sources:
      - MacroChallengeTeam2
    dependencies:
      - package: RxSwift
      - package: SnapKit
      - package: SocketIO
