name: MacroChallengeTeam2
options:
  bundleIdPrefix: com.namanya-apa
packages:
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.5.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.6.0
  SocketIO:
    url: https://github.com/socketio/socket.io-client-swift
    from: 16.0.1
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    from: 3.5.0
  Auth0:
    url: https://github.com/auth0/Auth0.swift
    from: 2.3.2
targets:
  Macro Challenge Team2:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    settings:
      INFOPLIST_FILE: MacroChallengeTeam2/Info.plist
      TARGETED_DEVICE_FAMILY: 2
    postCompileScripts:
      - path: swiftlint.sh
        name: SwiftLint
        basedOnDependencyAnalysis: false
    sources:
      - MacroChallengeTeam2
    dependencies:
      - package: RxSwift
      - package: SnapKit
      - package: SocketIO
      - package: Lottie
      - package: Auth0
